// Legal brief generator — a RICH, multi-section healthcare-fraud investigation
// brief built DETERMINISTICALLY from the case + detector findings.
//
// Pure module: no Node/server imports, no network, no LLM. Safe to import from
// client components AND from a regen script. The live path (textgen.ts) builds
// this deterministic brief, then optionally appends an LLM narrative from Corti
// Guided Docs as a final "Narrative Analysis (generated live)" section.
//
// Output convention: plain text. Major section headers are lines beginning with
// "## ". Sub-headers "### ". Body lines are plain paragraphs / bullets ("- ").
// The UI splits on "## " to render headers distinctly. Hedged throughout: this
// is a preliminary AI assessment, never a legal conclusion.

/** Provider facts available to the brief (all optional — surfaces pass what they have). */
export interface BriefProvider {
  name?: string;
  npi?: string;
  specialty?: string;
  state?: string;
}

/** A billed code line for the brief. */
export interface BriefCode {
  code: string;
  description: string;
  charge?: number;
}

/** The case-level finding (verdict). Surfaces derive this from
 *  CaseResult.findings[0] OR pass a fallback when findings is empty (the
 *  precomputed JSON stores the finding under `finding` singular, which
 *  normalizePrecomputed does not always populate into findings[]). */
export interface BriefFinding {
  fraudType: string;
  /** "fraud" | "error" | "clean" — the verdict. */
  verdict: string;
  confidence: number; // 0-1
  summary?: string;
  details?: string[];
  rationale?: string;
  dollarImpact?: number;
  groundingScore?: number;
}

/** A per-code retrace analysis (from CaseResult.code_analyses). */
export interface BriefAnalysis {
  code: string;
  description: string;
  /** "exact" | "extra" | "missing" | "mismatch". */
  match: string;
  agreeability: number; // 0-100
  /** "supported" | "weakly_supported" | "unsupported" | "contradicted". */
  grounding: string;
  noteExcerpts: string[];
  rationale?: string;
  confidence: number; // 0-1
}

export interface BuildLegalBriefOpts {
  caseId: string;
  provider?: BriefProvider;
  encounterDate?: string;
  clinicalNote?: string;
  billedCodes?: BriefCode[];
  finding: BriefFinding;
  analyses?: BriefAnalysis[];
  totalImpact?: number;
  detected?: boolean;
  /** Optional LLM-filled narrative from a live Guided Docs run, appended as a
   *  final section. When absent, the brief is fully deterministic. */
  liveNarrative?: string;
}

const HEDGE =
  "This is a preliminary investigation assessment generated by automated analysis of billing claims and clinical documentation. It does not constitute a legal conclusion or a determination of fraud, and mere coding discrepancies do not, by themselves, establish a violation.";

const FRAUD_TYPE_LABELS: Record<string, string> = {
  upcoding: "Upcoding",
  unbundling: "Unbundling",
  phantom: "Phantom Billing",
  dx_inflation: "Diagnosis Inflation",
  cloning: "Note Cloning",
  clean: "No anomaly detected",
};

function fraudLabel(t: string): string {
  return FRAUD_TYPE_LABELS[t] ?? t.replace(/_/g, " ");
}

function groundingLabel(g: string): string {
  switch (g) {
    case "supported":
      return "Supported";
    case "weakly_supported":
      return "Weakly supported";
    case "unsupported":
      return "Unsupported";
    case "contradicted":
      return "Contradicted";
    default:
      return g;
  }
}

function matchLabel(m: string): string {
  switch (m) {
    case "exact":
      return "Common (matched)";
    case "extra":
      return "Over-billed (billed, not predicted)";
    case "missing":
      return "Under-billed (predicted, not billed)";
    case "mismatch":
      return "Mismatched";
    default:
      return m;
  }
}

function matterClass(verdict: string): string {
  if (verdict === "fraud") return "credible allegation of fraud";
  if (verdict === "error") return "compliance concern";
  return "billing discrepancy";
}

/** Format a USD amount compactly, e.g. "$10,125". */
function usd(n: number | undefined): string {
  if (n == null || !isFinite(n) || n === 0) return "$0";
  return `$${Math.round(n).toLocaleString("en-US")}`;
}

/** Format a confidence 0-1 as a percentage. */
function pct(c: number | undefined): string {
  if (c == null || !isFinite(c)) return "—";
  return `${Math.round(c * 100)}%`;
}

/** A short clinical-note summary (first ~2 sentences), to keep the brief
 *  grounded without dumping the whole note. */
function summarizeNote(note: string | undefined): string {
  if (!note) return "Clinical note not provided.";
  const clean = note.replace(/\s+/g, " ").trim();
  if (clean.length <= 320) return clean;
  // Cut at a sentence boundary near 320 chars if possible.
  const slice = clean.slice(0, 320);
  const lastDot = slice.lastIndexOf(".");
  if (lastDot > 160) return `${slice.slice(0, lastDot + 1)} […]`;
  return `${slice} […]`;
}

/** Build the rich, multi-section legal brief as plain text. */
export function buildLegalBrief(opts: BuildLegalBriefOpts): string {
  const {
    caseId,
    provider,
    encounterDate,
    clinicalNote,
    billedCodes,
    finding,
    analyses = [],
    totalImpact,
    detected,
    liveNarrative,
  } = opts;

  const fLabel = fraudLabel(finding.fraudType);
  const cls = matterClass(finding.verdict);
  const overBilled = analyses.filter((a) => a.match === "extra" || a.match === "mismatch");
  const matched = analyses.filter((a) => a.match === "exact");
  const underBilled = analyses.filter((a) => a.match === "missing");
  const hasAnomalies = overBilled.length > 0;
  const exposure = totalImpact ?? finding.dollarImpact ?? 0;

  const lines: string[] = [];

  // ── Header ──────────────────────────────────────────────────────────────
  lines.push("## PRIVILEGED HEALTHCARE BILLING INVESTIGATION — LEGAL BRIEF");
  lines.push("");
  lines.push(HEDGE);
  lines.push("");

  // ── I. Matter Identification & Classification ─────────────────────────────
  lines.push("## I. Matter Identification & Classification");
  lines.push("");
  lines.push(`- Matter: ${cls.toUpperCase()}.`);
  lines.push(`- Case ID: ${caseId}`);
  if (provider?.name) lines.push(`- Provider: ${provider.name}`);
  if (provider?.npi) lines.push(`- NPI: ${provider.npi}`);
  if (provider?.specialty) lines.push(`- Specialty: ${provider.specialty}`);
  if (provider?.state) lines.push(`- State: ${provider.state}`);
  if (encounterDate) lines.push(`- Encounter date: ${encounterDate}`);
  lines.push(`- Allegation category: ${fLabel}.`);
  lines.push(`- Detector verdict: ${finding.verdict === "fraud" ? "Likely fraud" : finding.verdict === "error" ? "Possible error" : "No anomaly"} (confidence ${pct(finding.confidence)}).`);
  lines.push("");

  // ── II. Executive Summary ────────────────────────────────────────────────
  lines.push("## II. Executive Summary");
  lines.push("");
  const summary = finding.summary ?? (hasAnomalies
    ? `The detector identified ${overBilled.length} billed code${overBilled.length === 1 ? "" : "s"} not supported by the clinical documentation, consistent with ${fLabel.toLowerCase()}.`
    : "The detector found no billing discrepancies between the submitted codes and the clinical documentation.");
  lines.push(summary);
  lines.push("");
  if (exposure > 0) {
    lines.push(`Projected financial exposure (single claim, pre-treble): ${usd(exposure)}. Under the False Claims Act, single-claim damages may be trebled (3×) and a per-claim civil penalty may apply in addition to damages.`);
  }
  lines.push("");

  // ── III. Factual Background ──────────────────────────────────────────────
  lines.push("## III. Factual Background");
  lines.push("");
  if (encounterDate) lines.push(`The matter concerns an encounter on ${encounterDate}.`);
  if (clinicalNote) {
    lines.push("### Clinical documentation (summary)");
    lines.push("");
    lines.push(summarizeNote(clinicalNote));
    lines.push("");
  }
  if (billedCodes && billedCodes.length > 0) {
    lines.push("### Submitted (billed) codes");
    lines.push("");
    for (const b of billedCodes) {
      const charge = b.charge != null && b.charge > 0 ? ` — ${usd(b.charge)}` : "";
      lines.push(`- ${b.code}: ${b.description}${charge}`);
    }
    lines.push("");
  }

  // ── IV. Coding Discrepancy Analysis ───────────────────────────────────────
  lines.push("## IV. Coding Discrepancy Analysis (set-intersection + retrace)");
  lines.push("");
  if (analyses.length === 0) {
    lines.push("No per-code retrace analysis was available for this matter.");
    lines.push("");
  } else {
    lines.push(`The coding expert predicted codes from the clinical note and compared them against the billed codes via set-intersection. Result: ${matched.length} common (matched), ${overBilled.length} over-billed (billed, not predicted), ${underBilled.length} under-billed (predicted, not billed).`);
    lines.push("");
    if (matched.length > 0) {
      lines.push("### Common (matched — grounded in the note)");
      lines.push("");
      for (const a of matched) {
        lines.push(`- ${a.code}: ${a.description} — ${groundingLabel(a.grounding)}.`);
      }
      lines.push("");
    }
    if (overBilled.length > 0) {
      lines.push("### Over-billed codes (billed, not predicted — under investigation)");
      lines.push("");
      for (const a of overBilled) {
        lines.push(`### ${a.code} — ${a.description}`);
        lines.push("");
        lines.push(`- Set-intersection: ${matchLabel(a.match)}.`);
        lines.push(`- Grounding: ${groundingLabel(a.grounding)}.`);
        lines.push(`- Agreeability score: ${Math.round(a.agreeability)}/100 (0 = not defensible / likely fraud, 100 = minor miss).`);
        lines.push(`- Detector confidence: ${pct(a.confidence)}.`);
        if (a.rationale) {
          lines.push(`- Rationale: ${a.rationale}`);
        }
        if (a.noteExcerpts.length > 0) {
          lines.push("- Note excerpts cited by the retrace agent:");
          for (const ex of a.noteExcerpts.slice(0, 5)) {
            lines.push(`  - “${ex}”`);
          }
        }
        lines.push("");
      }
    }
    if (underBilled.length > 0) {
      lines.push("### Under-billed codes (predicted, not billed)");
      lines.push("");
      for (const a of underBilled) {
        lines.push(`- ${a.code}: ${a.description} — ${groundingLabel(a.grounding)}.`);
      }
      lines.push("");
    }
  }

  // ── V. Statutory Framework ───────────────────────────────────────────────
  lines.push("## V. Statutory Framework");
  lines.push("");
  lines.push("### Civil False Claims Act (31 U.S.C. § 3729)");
  lines.push("");
  lines.push("- § 3729(a)(1)(A): liability for knowingly presenting, or causing to be presented, a false or fraudulent claim for payment or approval.");
  lines.push("- § 3729(a)(1)(B): liability for knowingly making, using, or causing to be made or used, a false record or statement material to a false or fraudulent claim.");
  lines.push("- § 3729(a)(1)(G): reverse false claims — knowingly concealing or avoiding an obligation to pay the government.");
  lines.push("- § 3729(b)(1): \"knowingly\" means actual knowledge, deliberate ignorance, or reckless disregard of the truth or falsity of the information (no specific intent to defraud required).");
  lines.push("- § 3729(b)(4): \"material\" means having a natural tendency to influence, or be capable of influencing, the payment or receipt of money or property.");
  lines.push("- § 3729(a)(1): liability includes treble (3×) damages and a civil penalty for each false claim, adjusted for inflation (the per-claim penalty is set by DOJ rulemaking and changes periodically; cited here as a range, not a fixed figure).");
  lines.push("");
  lines.push("### Qui Tam & Relator Provisions (31 U.S.C. § 3730)");
  lines.push("");
  lines.push("- § 3730(b): a private person (relator) may bring a qui tam action on behalf of the United States.");
  lines.push("- § 3730(d)(2): if the government declines to intervene and the relator proceeds, the relator share is 25–30% of the proceeds.");
  lines.push("- § 3730(d)(1): if the government intervenes, the relator share is 15–25% of the proceeds.");
  lines.push("- § 3730(h): anti-retaliation protection for relators/employees who act in furtherance of a qui tam action.");
  lines.push("- § 3731(b): a civil FCA action must be brought within 6 years of the violation, or within 3 years of when the material facts became known (not to exceed 10 years).");
  lines.push("");
  lines.push("### Criminal Healthcare Fraud (18 U.S.C. § 1347)");
  lines.push("");
  lines.push("- § 1347: whoever knowingly and willfully executes, or attempts to execute, a scheme to defraud any healthcare benefit program, or to obtain money/property by means of false or fraudulent pretenses, is subject to criminal penalties. Requires specific intent to defraud (a higher scienter than the civil FCA).");
  lines.push("");
  lines.push("### Administrative Exclusion & Anti-Kickback (42 U.S.C. § 1320a-7)");
  lines.push("");
  lines.push("- § 1320a-7: HHS-OIG authority to exclude providers from participation in federal healthcare programs for program-related crimes, patient abuse, fraud, or other listed grounds.");
  lines.push("- § 1320a-7b: the federal Anti-Kickback Statute — prohibits remuneration for referrals of items/services payable by federal healthcare programs (relevant where the billing pattern suggests inducement).");
  lines.push("");

  // ── VI. Scienter & Knowledge Analysis ────────────────────────────────────
  lines.push("## VI. Scienter & Knowledge Analysis");
  lines.push("");
  lines.push("Under the civil FCA, liability attaches to a person who acts with actual knowledge, deliberate ignorance, or reckless disregard of the falsity of the claim. No specific intent to defraud is required. The detector's findings are evaluated against this standard below; this assessment draws inferences cautiously and does not assert intent as established fact.");
  lines.push("");
  if (hasAnomalies) {
    const lowAgree = overBilled.filter((a) => a.agreeability < 30);
    if (lowAgree.length > 0) {
      lines.push(`- ${lowAgree.length} over-billed code${lowAgree.length === 1 ? "" : "s"} received an agreeability score below 30/100, indicating the retrace agent found them not defensible from the documentation. A pattern of low-agreeability codes billed repeatedly may be consistent with reckless disregard or deliberate ignorance, though alternative explanations (documentation lapses, coding errors) cannot be excluded on this record alone.`);
    } else {
      lines.push("- The over-billed codes received moderate agreeability scores, more consistent with documentation or coding errors than with knowing misconduct; further review of the provider's pattern across claims would be needed to assess scienter.");
    }
  } else {
    lines.push("- No over-billed codes were identified; scienter analysis is not applicable on this record.");
  }
  lines.push("");

  // ── VII. Materiality Analysis ───────────────────────────────────────────
  lines.push("## VII. Materiality Analysis");
  lines.push("");
  lines.push("Under Universal Health Services, Inc. v. United States ex rel. Escobar, 136 S. Ct. 1989 (2016), the FCA's materiality requirement is rigorous: the nondisclosed noncompliance must be material to the government's payment decision, and materiality may bar a claim even at the pleading stage. Implied false certification can establish falsity when a provider makes specific representations about services but omits material noncompliance.");
  lines.push("");
  if (hasAnomalies) {
    lines.push(`- The ${overBilled.length} over-billed code${overBilled.length === 1 ? "" : "s"} represent clinical conditions or services that the documentation does not support. Whether these omissions are material turns on whether the payer would have paid (or paid the amount) had the true documentation been known. Diagnosis codes used for risk adjustment carry a heightened materiality nexus because they directly drive capitated payment.`);
  } else {
    lines.push("- No unsupported codes were identified; materiality analysis is not applicable on this record.");
  }
  lines.push("");

  // ── VIII. Damages & Exposure Assessment ──────────────────────────────────
  lines.push("## VIII. Damages & Exposure Assessment");
  lines.push("");
  lines.push(`- Single-claim overpayment (deterministic): ${usd(exposure)}.`);
  if (totalImpact != null && totalImpact > 0 && totalImpact !== exposure) {
    lines.push(`- Projected/extrapolated exposure (frequency × penalty): ${usd(totalImpact)}.`);
  }
  lines.push("- Treble damages under § 3729(a)(1) would multiply single-claim damages by 3×, plus a per-claim civil penalty (inflation-adjusted; set by DOJ rulemaking) for each false claim submitted.");
  lines.push("- Exposure estimates are preliminary, based on the documented encounter and the detector's per-code analysis; actual exposure depends on the volume of similar claims, the government's election of remedies, and any settlement or self-disclosure credit.");
  lines.push("");

  // ── IX. Evidence Index ────────────────────────────────────────────────────
  lines.push("## IX. Evidence Index");
  lines.push("");
  if (hasAnomalies) {
    lines.push("Per-code evidence cited by the retrace agent (verbatim note excerpts):");
    lines.push("");
    for (const a of overBilled) {
      lines.push(`### ${a.code} (${groundingLabel(a.grounding)}, agreeability ${Math.round(a.agreeability)}/100)`);
      if (a.noteExcerpts.length > 0) {
        for (const ex of a.noteExcerpts.slice(0, 5)) {
          lines.push(`- “${ex}”`);
        }
      } else {
        lines.push("- (no excerpts cited)");
      }
      lines.push("");
    }
  } else {
    lines.push("No anomalous codes were identified; no evidence index applies.");
    lines.push("");
  }
  lines.push(`- Detector confidence (case-level): ${pct(finding.confidence)}.`);
  if (typeof detected === "boolean") {
    lines.push(
      detected
        ? "- Honesty signal: the detector independently arrived at the planted fraud category (no answer-key leakage)."
        : "- Honesty signal: fraud was detected, though the detector's category label differed from the planted category.",
    );
  }
  lines.push("");

  // ── X. Recommended Actions ────────────────────────────────────────────────
  lines.push("## X. Recommended Actions");
  lines.push("");
  if (finding.verdict === "fraud") {
    lines.push("- Referral: refer the matter to the U.S. Department of Justice, Civil Division (for potential civil FCA intervention), and/or the appropriate U.S. Attorney's Office. A qui tam relator may proceed independently if the government declines (§ 3730).");
    lines.push("- State referral: where the claim involves a state Medicaid program, refer to the state Medicaid Fraud Control Unit (MFCU).");
  } else if (finding.verdict === "error") {
    lines.push("- Compliance review: treat as a compliance concern pending review of the provider's pattern across claims. Consider OIG Provider Self-Disclosure if the provider identifies and reports the overpayment.");
  } else {
    lines.push("- No referral recommended on this record. Document the review and close, or monitor for a pattern across future claims.");
  }
  lines.push("- Document preservation: advise the provider to preserve billing records, clinical documentation, and correspondence relevant to the encounter and any similar claims.");
  lines.push("- Remediation: where overpayment is identified, recommend repayment and, where appropriate, a compliance-plan revision and staff education on the affected code(s).");
  lines.push("- All actions are recommendations only; the decision to refer, investigate, or disclose rests with counsel and the relevant government authority.");
  lines.push("");

  // ── XI. Limitations & Disclaimers ─────────────────────────────────────────
  lines.push("## XI. Limitations & Disclaimers");
  lines.push("");
  lines.push(`- ${HEDGE}`);
  lines.push("- This brief is generated by automated analysis and requires review by qualified counsel before any referral, disclosure, or action is taken.");
  lines.push("- Coding discrepancies, unsupported codes, and low agreeability scores are evidence of potential issues; they do not establish that a violation occurred or that any person acted with the requisite state of mind.");
  lines.push("- Statute of limitations: civil FCA actions are subject to the limitations periods in 31 U.S.C. § 3731(b); timely referral preserves the government's and a relator's rights.");
  lines.push("- Financial exposure figures are estimates and may differ materially from any amount ultimately recoverable.");
  lines.push("");

  // ── XII. Narrative Analysis (generated live) ──────────────────────────────
  if (liveNarrative && liveNarrative.trim().length > 0) {
    lines.push("## XII. Narrative Analysis (generated live via Guided Docs)");
    lines.push("");
    lines.push(liveNarrative.trim());
    lines.push("");
  }

  return lines.join("\n").trim() + "\n";
}

/** Extract a BriefFinding from a CaseResult.findings[0], with fallbacks for
 *  precomputed cases where findings[] is empty (the raw `finding` lives in the
 *  precomputed JSON under a different shape). Surfaces call this, then pass
 *  overrides (e.g. the tour case's fraudType) when the CaseResult has no
 *  findings. */
export function findingFromResult(
  result: { findings?: Array<{ fraud_type?: string; intent?: string; verdict?: string; confidence?: number; rationale?: string; dollar_impact?: number; grounding_score?: number; analysis?: { verdict?: string } }> } | null | undefined,
  overrides?: { fraudType?: string; verdict?: string; confidence?: number; summary?: string; rationale?: string },
): BriefFinding {
  const f = result?.findings?.[0];
  const fraudType = f?.fraud_type ?? overrides?.fraudType ?? "clean";
  const verdict = f?.analysis?.verdict ?? f?.intent ?? overrides?.verdict ?? "error";
  const confidence = f?.confidence ?? overrides?.confidence ?? 0;
  return {
    fraudType,
    verdict,
    confidence,
    summary: overrides?.summary ?? f?.rationale,
    rationale: overrides?.rationale ?? f?.rationale,
    dollarImpact: f?.dollar_impact,
    groundingScore: f?.grounding_score,
  };
}
