// Legal brief generator — first-class output for the attorney/relator ICP.
// Hybrid: deterministic 13-section skeleton (static FCA/criminal/administrative
// statute references + qui-tam ranges + hedged microcopy) + LLM-filled
// case-specific reasoning via Corti Guided Documents (POST /v2/documents).
//
// This showcases the textgen capability. Proven on staging-eu (~0.011 credits).
// See memory/corti-api-surfaces.md.

import type { Case } from "./types";
import { CortiClient, type DocSection } from "./pipeline";
import type { CaseFinding } from "./agents/judgement";

const HEDGE = "This is a preliminary investigation assessment generated by automated analysis of billing claims and clinical documentation. It does not constitute a legal conclusion or a determination of fraud.";

/** Generate the legal/referral brief via Guided Docs. */
export async function generateLegalBrief(
  client: CortiClient,
  c: Case,
  finding: CaseFinding,
  timeoutMs = 90_000,
): Promise<string> {
  const sections = buildBriefSections(c, finding);
  const contextText = buildBriefContext(c, finding);
  const resp = await client.generateDocument(sections, contextText, "FraudLens legal brief", timeoutMs);
  // Prepend the deterministic statutory skeleton (static, vetted legal references).
  return `${buildStatutorySkeleton(finding)}\n\n${resp.text}`;
}

/** The deterministic 13-section skeleton with static legal references. */
function buildStatutorySkeleton(finding: CaseFinding): string {
  const matterClass = finding.verdict === "fraud" ? "credible allegation" : finding.verdict === "error" ? "compliance concern" : "billing error";
  return [
    `# PRIVILEGED HEALTHCARE BILLING INVESTIGATION AND REFERRAL ASSESSMENT`,
    ``,
    `## I. Matter Classification`,
    `Classification: ${matterClass.toUpperCase()}.`,
    `This assessment evaluates billing patterns against clinical documentation. The presence of coding discrepancies does not, by itself, establish a violation.`,
    ``,
    `## II. Regulatory Framework`,
    `- Civil False Claims Act (31 U.S.C. § 3729): liability for knowingly submitting false claims to federal healthcare programs.`,
    `- Criminal Healthcare Fraud (18 U.S.C. § 1347): knowingly executing a scheme to defraud a healthcare benefit program.`,
    `- Administrative Exclusion (42 U.S.C. § 1320a-7): HHS-OIG authority to exclude providers from federal programs.`,
    ``,
    `## III. Qui Tam / Relator Considerations (COUNSEL ONLY)`,
    `Under 31 U.S.C. § 3730, a private relator may bring a qui tam action. Relator share: 15-25% if the government intervenes; 25-30% if the relator proceeds independently.`,
    `Anti-retaliation protection: 31 U.S.C. § 3730(h).`,
    ``,
    HEDGE,
    ``,
    `## IV–XIII. Case-Specific Analysis (generated below)`,
  ].join("\n");
}

/** The dynamic sections the LLM fills from the case findings. */
function buildBriefSections(c: Case, finding: CaseFinding): DocSection[] {
  return [
    {
      heading: "Factual Basis and Specific Findings",
      instructions: {
        contentPrompt: `Summarize the specific billing discrepancies found in this case. Fraud type: ${finding.fraudType}. Verdict: ${finding.verdict}. Confidence: ${finding.confidence}. Detail the codes involved and why they are unsupported by the clinical note.`,
        writingStylePrompt: "Clinical, precise, non-conclusory. Avoid asserting intent as fact.",
      },
      outputSchema: { type: "string" },
    },
    {
      heading: "Evidence Summary",
      instructions: {
        contentPrompt: "Summarize the clinical documentation evidence that supports or refutes the billed codes. Reference the per-code agreeability and grounding assessments.",
        writingStylePrompt: "Objective, evidence-led.",
      },
      outputSchema: { type: "string" },
    },
    {
      heading: "FCA Exposure Assessment",
      instructions: {
        contentPrompt: "Assess the potential False Claims Act exposure based on the detected billing pattern. Note that coding discrepancies alone do not establish scienter.",
        writingStylePrompt: "Cautious, hedged. Use 'may' and 'appears to' rather than definitive assertions.",
      },
      outputSchema: { type: "string" },
    },
    {
      heading: "Financial Exposure and Remediation",
      instructions: {
        contentPrompt: "Estimate the financial exposure and recommend remediation steps (repayment, self-disclosure, compliance plan revision).",
        writingStylePrompt: "Practical, actionable.",
      },
      outputSchema: { type: "string" },
    },
    {
      heading: "Provider Response Assessment",
      instructions: {
        contentPrompt: "Assess what the provider's response or explanation might be, and how the investigation should proceed.",
        writingStylePrompt: "Even-handed, investigative.",
      },
      outputSchema: { type: "string" },
    },
  ];
}

function buildBriefContext(c: Case, finding: CaseFinding): string {
  return [
    `Case: ${c.case_id}`,
    `Provider: ${c.provider_id}`,
    `Encounter date: ${c.encounter.date}`,
    `Clinical note: ${c.clinical_note}`,
    `Billed procedures: ${c.submitted_codes.procedures.map((p) => `${p.code} (${p.description})`).join(", ")}`,
    `Billed diagnoses: ${c.submitted_codes.dx.map((d) => `${d.code} (${d.description})`).join(", ")}`,
    `Fraud type: ${finding.fraudType}`,
    `Verdict: ${finding.verdict}`,
    `Confidence: ${finding.confidence}`,
    `Summary: ${finding.summary}`,
    `Details: ${finding.details.join("; ")}`,
  ].join("\n");
}
